
from cpu import (
    WeirdoCPU,
    PATH_ALU, PATH_MEM, PATH_BR,
    ALU_ADD, ALU_ADDI, ALU_SUB, ALU_AND, ALU_OR, ALU_XOR, ALU_SLL, ALU_SRL, ALU_SRA,
    MEM_LD, MEM_ST,
    BR_BEQ, BR_BNE, BR_JMP,
)