set(ASM_FRONTEND_SRC ${ASM_FRONTEND_SRC}

	${CMAKE_CURRENT_SOURCE_DIR}/lexer.c
	${CMAKE_CURRENT_SOURCE_DIR}/parser.c
	${CMAKE_CURRENT_SOURCE_DIR}/inter.c

)

set(CMAKE_BUILD_TYPE Debug)


add_library(ASM_FRONTEND STATIC ${ASM_FRONTEND_SRC})



target_include_directories(ASM_FRONTEND
	PUBLIC
	${CMAKE_CURRENT_SOURCE_DIR}/
	ASM_COMMONS
	ASM_INTERNALS
)


target_link_libraries(ASM_FRONTEND
	PUBLIC
	ASM_COMMONS
	ASM_INTERNALS
)
