
set(WCC_COMMONS_SRC ${WCC_COMMONS_SRC}

	${CMAKE_CURRENT_SOURCE_DIR}/WCC_map.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_string.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_token.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_file.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_lexer.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_alloc.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_string.c
	${CMAKE_CURRENT_SOURCE_DIR}/WCC_memory.c

)
set(CMAKE_BUILD_TYPE Debug)

add_library(WCC_COMMONS STATIC
	${WCC_COMMONS_SRC}
)


target_include_directories(WCC_COMMONS
	PUBLIC
	${CMAKE_CURRENT_SOURCE_DIR}/
	WCC_CONSTANTS

)

target_link_libraries(WCC_COMMONS
	PUBLIC
	WCC_CONSTANTS
)


