set(ASM_INTERNALS_SRC ${ASM_INTERNALS_SRC}

	${CMAKE_CURRENT_SOURCE_DIR}/entry.c
	${CMAKE_CURRENT_SOURCE_DIR}/instruction.c
	${CMAKE_CURRENT_SOURCE_DIR}/metaop.c
	${CMAKE_CURRENT_SOURCE_DIR}/decoder.c
	${CMAKE_CURRENT_SOURCE_DIR}/reference.c
	${CMAKE_CURRENT_SOURCE_DIR}/segment.c
	${CMAKE_CURRENT_SOURCE_DIR}/scope.c
	${CMAKE_CURRENT_SOURCE_DIR}/symbol.c
	${CMAKE_CURRENT_SOURCE_DIR}/directive.c
	${CMAKE_CURRENT_SOURCE_DIR}/module.c
	${CMAKE_CURRENT_SOURCE_DIR}/psudeoop.c
	${CMAKE_CURRENT_SOURCE_DIR}/keywords.c

)



set(CMAKE_BUILD_TYPE Debug)


add_library(ASM_INTERNALS STATIC ${ASM_INTERNALS_SRC})



target_include_directories(ASM_INTERNALS
	PUBLIC
	${CMAKE_CURRENT_SOURCE_DIR}/
	ASM_COMMONS

)


target_link_libraries(ASM_INTERNALS
	PUBLIC
	ASM_COMMONS
)
